config/routes.rb
Rails.application.routes.draw do
  get '/games' => 'games#index'
  get '/games/attack' => 'games#attack'
  devise_for :users
  root to: 'games#index'
  resources :games do
    resources :locations
    resources :players
  end

  resources :locations do
    resources :enemies
  end
  # resources :users do
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  belongs_to :location
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :players, dependent: :destroy
  has_many :locations, dependent: :destroy

  def start
    return '/games'
  end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :enemies, dependent: :destroy
  belongs_to :game
  validates :name, presence: true

end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :location
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController

  def index
    @location = Location.find(params[:location_id])
    enemy_types = ["Skeleton", "Zombie", "Ghoul", "Kim Jong Un"]

    rand(3..5).times do
      @enemy = Enemy.new({:type_of => enemy_types[rand(0..3)], :health => 100})
      @enemy.location_id = @location.id
      @enemy.selected = false
      @enemy.alive = true
      if @enemy.save
        flash[:notice] = "Enemy successfully added!"
      end
    end
    redirect_to game_path(id: @location.game_id)
  end

  def update
    @selected_enemies = Enemy.where(selected: true)
    @selected_enemies.each do |enemy|
      enemy.selected = false
      enemy.save
    end

    @location = Location.find(params[:location_id])
    @enemy = Enemy.find(params[:id])
    @enemy.selected = true
    @enemy.save
    redirect_to edit_game_path(id: @location.game_id)
  end

  private
  def enemy_params
    params.require(:enemy).permit(:name, :location_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    if current_user
      @games = Game.where(user_id: current_user.id).order("id ASC")
    end
    render :index
  end

  def create
    @game = Game.new
    @game.user_id = current_user.id
    @game.current_player = 0
    @game.save
    redirect_to games_path
  end

  def show
    if current_user
      @game = Game.find(params[:id])
      @locations = Location.where(game_id: @game.id)
      @players = Player.where(game_id: @game.id)
    end
  end

  def edit
    @game = Game.find(params[:id])
    @players = Player.where(game_id: @game.id)
    @location = Location.find(@players[0].location_id)
    @enemies = Enemy.where(location_id: @location.id).order("id DESC")
    render :edit
  end

  def enemy_attack(game_id, location_id)
    @location = Location.find(location_id)
    @enemies = Enemy.where(location_id: location_id).order("id DESC")

    @enemies.each do |enemy|
      players = Player.where(game_id: @game.id).where("health > ?", 0)
      if players.any?
        randomPlayer = players[rand(0..players.length-1)]
        randomPlayer.health -= rand(1..50)
        if randomPlayer.health <= 0
          randomPlayer.alive = false
          randomPlayer.health = 0
        end
        randomPlayer.save
      end
    end
  end

  def attack
    @game = Game.find(params[:id])
    @players = Player.where(game_id: @game.id)
    @player = @players[@game.current_player]
    @enemies = Enemy.where(location_id: @player.location_id)
    @enemy = Enemy.where(selected: true).limit(1)[0]
    @enemy.health -= rand(1..50)
    if @enemy.health <= 0
      @enemy.alive = false
      @enemy.health = 0
    end
    @enemy.save

    @game.current_player += 1

    while !(@game.current_player >= @players.length) && @players[@game.current_player].alive == false
      @game.current_player += 1
    end
    if @game.current_player >= @players.length
      self.enemy_attack(@game.id, @player.location_id)

      @game.current_player = 0
    end
    @game.save

    if self.check_for_player_win(@enemies)
      render :player_win
    elsif self.check_for_player_win(@players)
      render :enemy_win
    else
      redirect_to edit_game_path(id: @game.id)
    end
  end

  def check_for_player_win(enemies)
    win = true
    enemies.each do |enemy|
      if enemy.health > 0
        win = false
      end
    end
    win
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if current_user
      @locations = Location.where(user_id: current_user.id)
      @players = Player.where(user_id: current_user.id)
    end
    render :index
  end

  def new
    @location = Location.new
    @game = Game.find(params[:game_id])
    render :new
  end

  def create
    @game = Game.find(params[:game_id])
    @location = Location.new(location_params)
    if @location.save
      flash[:notice] = "Location successfully added!"
      redirect_to location_enemies_path(location_id: @location.id)
    else
      render :new
    end
  end

  private
  def location_params
    params.require(:location).permit(:name, :game_id)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
    render :index
  end

  def new
    @game = Game.find(params[:game_id])
    @player = Player.new
    render :new
  end

  def create
    @game = Game.find(params[:game_id])
    @player = Player.new(player_params)
    @player.health = 100
    @player.alive = true
    if @player.save
      flash[:notice] = "player successfully added!"
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def show
    @player = Player.find(params[:id])
    @location = Location.find(@player.location_id)
    render :show
  end

  private
  def player_params
    params.require(:player).permit(:name, :health, :location_id, :game_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_controller_helper.rb
module GamesControllerHelper
end

app/views/games/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        <h3>Player Team</h3>
      </div>
      <div class="card-body">
        <% @players.each_with_index do |player, index| %>
        <div class="card">
          <% if index == @game.current_player%>
            <div class="card-body selected-player">
          <% else %>
            <% if player.alive %>
              <div class="card-body">
            <% else %>
              <div class="card-body dead-player">
            <% end %>
          <% end %>
            <%= player.name %>
            <br>
            Health: <%= player.health %> / 100
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h3>Controls</h3>

      </div>
      <div class="card-body">
        <h3>Location: <%= @location.name %></h3>
        <h4> Current Player: <%= @players[@game.current_player].name %></h4>

        <%= button_to "Attack", games_attack_path, method: :get, params: { id: @game.id } %>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        <h3>Enemy Team</h3>
      </div>
      <div class="card-body">
        <% @enemies.each_with_index do |enemy, index| %>
        <%= link_to location_enemy_path(id: enemy.id, location_id: enemy.location_id), method: :patch do %>
        <div class="card">
          <% if enemy.alive == false %>
            <div class="card-body dead-player" id="<%= index %>">
          <% else%>
            <% if enemy.selected%>
              <div class="card-body selected-enemy" id="<%= index %>">
            <% else%>
              <div class="card-body" id="<%= index %>">
            <% end %>

          <% end %>

          <%= enemy.type_of %>
          <br>
          Health: <%= enemy.health %> / 100
            </div>
          </div>
          <% end%>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/games/enemy_win.html.erb
<h2> The Enemies defeated all the Players</h2>

app/views/games/index.html.erb
<h1>Action Blasters</h1>
<% if current_user %>

  <h2>Games</h2>
    <% if @games.any? %>
    <ul>
      <% @games.each_with_index do |game, index| %>
        <li><%= link_to "Game Save: #{index+1}", game_path(id: game.id) %></li>
      <% end %>
  </ul>
  <% else %>
    <p>No games added yet.</p>
  <% end %>

  <p><%= link_to "Create a Game", games_path, method: :post %></p>

<% else %>
  <br>
  <h3>Please Sign in to view game details</h3>
  <br>
<% end %>

app/views/games/player_win.html.erb
<h2> The Players defeated all the Enemies</h2>

app/views/games/show.html.erb
<h1>Action Blasters</h1>
<% if current_user %>

  <h2>Locations</h2>
    <% if @locations.any? %>
    <ul>
      <% @locations.each do |location| %>
        <li><%= link_to location.name, game_location_path(location) %></li>
      <% end %>
  </ul>
  <% else %>
    <p>No locations added yet.</p>
  <% end %>
  <h2>Players</h2>
    <% if @players.any? %>
    <ul>
      <% @players.each do |player| %>
        <li><%= link_to player.name, game_player_path(player) %></li>
      <% end %>
  </ul>
  <% else %>
    <p>No players added yet.</p>
  <% end %>
  <p><%= link_to "Add an Location", new_game_location_path(@location, game_id: @game.id) %></p>
  <% if @locations.any? %>
  <p><%= link_to "Add a Player", new_game_player_path(@player, game_id: @game.id) %></p>
  <% end %>

  <% if @locations.any? && @players.any? %>
    <%= button_to "Start Game", edit_game_path, method: :get%>
  <% else%>
    <br><p>Add a location and a player to start the game</p>
  <% end%>
<% else %>
  <br>
  <h3>Please Sign in to view game details</h3>
  <br>
<% end %>

app/views/games/start.html.erb
<p>got here</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionBlasters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", '/users/sign_out', method: :delete %>
      <% else %>
      <%= link_to "Sign up", '/users/sign_up' %> | <%= link_to "Sign in", '/users/sign_in' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Action Blasters</h1>
<% if current_user %>
  <h2>Locations</h2>
    <% if @locations.any? %>
    <ul>
      <% @locations.each do |location| %>
        <li><%= link_to location.name, location_path(location) %></li>
      <% end %>
  </ul>
  <% else %>
    <p>No locations added yet.</p>
  <% end %>
  <h2>Players</h2>
    <% if @players.any? %>
    <ul>
      <% @players.each do |player| %>
        <li><%= link_to player.name, player_path(player) %></li>
      <% end %>
  </ul>
  <% else %>
    <p>No players added yet.</p>
  <% end %>
  <p><%= link_to "Add an Location", new_location_path(@location) %></p>
  <% if @locations.any? %>
  <p><%= link_to "Add a Player", new_player_path(@player) %></p>
  <% end %>

<% else %>
  <br>
  <h3>Please Sign in to view game details</h3>
  <br>
<% end %>

app/views/locations/new.html.erb
<h1>Add a new location</h1>
<%= form_for @location, :url => game_locations_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field :game_id, :value => @game.id%>

  <%= f.submit %>
<% end %>

app/views/players/new.html.erb
<h1>Add a new Player</h1>

<%= form_for @player, :url => game_players_path do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :location %><br>
  <%= f.select :location_id, Location.where(game_id: @game.id).collect {|p| [p.name, p.id]} %><br>
  <%= f.hidden_field :game_id, :value => @game.id%>
  <%= f.submit %>
<% end %>

app/views/players/show.html.erb
<h1> <%= @player.name %> </h1>
<h3> <%= @player.level %> </h3>
<h3> <%= @location.name %> </h3>